window.layouts = {
    en: [
      [
       { code: "Backquote", key: "`", shiftedKey: "~" },
       { code: "Digit1", key: "1", shiftedKey: "!" },
       { code: "Digit2", key: "2", shiftedKey: "@" },
       { code: "Digit3", key: "3", shiftedKey: "#" },
       { code: "Digit4", key: "4", shiftedKey: "$" },
       { code: "Digit5", key: "5", shiftedKey: "%" },
       { code: "Digit6", key: "6", shiftedKey: "^" },
       { code: "Digit7", key: "7", shiftedKey: "&" },
       { code: "Digit8", key: "8", shiftedKey: "*" },
       { code: "Digit9", key: "9", shiftedKey: "(" },
       { code: "Digit0", key: "0", shiftedKey: ")" },
       { code: "Minus", key: "-", shiftedKey: "_" },
       { code: "Equal", key: "=", shiftedKey: "+" }
      ],
  
      [
       { code: "KeyQ", key: "q", shiftedKey: "Q" },
       { code: "KeyW", key: "w", shiftedKey: "W" },
       { code: "KeyE", key: "e", shiftedKey: "E" },
       { code: "KeyR", key: "r", shiftedKey: "R" },
       { code: "KeyT", key: "t", shiftedKey: "T" },
       { code: "KeyY", key: "y", shiftedKey: "Y" },
       { code: "KeyU", key: "u", shiftedKey: "U" },
       { code: "KeyI", key: "i", shiftedKey: "I" },
       { code: "KeyO", key: "o", shiftedKey: "O" },
       { code: "KeyP", key: "p", shiftedKey: "P" },
       { code: "BracketLeft", key: "[", shiftedKey: "{" },
       { code: "BracketRight", key: "]", shiftedKey: "}" },
       { code: "Backslash", key: "\\", shiftedKey: "|" }     
      ],
      [
       { code: "KeyA", key: "a", shiftedKey: "A" },
       { code: "KeyS", key: "s", shiftedKey: "S" },
       { code: "KeyD", key: "d", shiftedKey: "D" },
       { code: "KeyF", key: "f", shiftedKey: "F" },
       { code: "KeyG", key: "g", shiftedKey: "G" },
       { code: "KeyH", key: "h", shiftedKey: "H" },
       { code: "KeyJ", key: "j", shiftedKey: "J" },
       { code: "KeyK", key: "k", shiftedKey: "K" },
       { code: "KeyL", key: "l", shiftedKey: "L" },
       { code: "Semicolon", key: ";", shiftedKey: ":" },
       { code: "Quote", key: "'", shiftedKey: "\"" }
      ],
      [
       { code: "KeyZ", key: "z", shiftedKey: "Z" },
       { code: "KeyX", key: "x", shiftedKey: "X" },
       { code: "KeyC", key: "c", shiftedKey: "C" },
       { code: "KeyV", key: "v", shiftedKey: "V" },
       { code: "KeyB", key: "b", shiftedKey: "B" },
       { code: "KeyN", key: "n", shiftedKey: "N" },
       { code: "KeyM", key: "m", shiftedKey: "M" },
       { code: "Comma", key: ",", shiftedKey: "<" },
       { code: "Period", key: ".", shiftedKey: ">" },
       { code: "Slash", key: "/", shiftedKey: "?" },     
      ],
    ],  
    ru: [
      [
       { code: "Backquote", key: "]", shiftedKey: "[" },
       { code: "Digit1", key: "1", shiftedKey: "!" },
       { code: "Digit2", key: "2", shiftedKey: "\"" },
       { code: "Digit3", key: "3", shiftedKey: "№" },
       { code: "Digit4", key: "4", shiftedKey: "%" },
       { code: "Digit5", key: "5", shiftedKey: ":" },
       { code: "Digit6", key: "6", shiftedKey: "," },
       { code: "Digit7", key: "7", shiftedKey: "." },
       { code: "Digit8", key: "8", shiftedKey: ";" },
       { code: "Digit9", key: "9", shiftedKey: "(" },
       { code: "Digit0", key: "0", shiftedKey: ")" },
       { code: "Minus", key: "-", shiftedKey: "_" },
       { code: "Equal", key: "=", shiftedKey: "+" }
      ],
  
      [
       { code: "KeyQ", key: "й", shiftedKey: "Й" },
       { code: "KeyW", key: "ц", shiftedKey: "Ц" },
       { code: "KeyE", key: "у", shiftedKey: "У" },
       { code: "KeyR", key: "к", shiftedKey: "К" },
       { code: "KeyT", key: "е", shiftedKey: "Е" },
       { code: "KeyY", key: "н", shiftedKey: "Н" },
       { code: "KeyU", key: "г", shiftedKey: "Г" },
       { code: "KeyI", key: "ш", shiftedKey: "Ш" },
       { code: "KeyO", key: "щ", shiftedKey: "Щ" },
       { code: "KeyP", key: "з", shiftedKey: "З" },
       { code: "BracketLeft", key: "х", shiftedKey: "Х" },
       { code: "BracketRight", key: "ъ", shiftedKey: "Ъ" },
       { code: "Backslash", key: "ё", shiftedKey: "Ё" }     
      ],
      [
       { code: "KeyA", key: "ф", shiftedKey: "Ф" },
       { code: "KeyS", key: "ы", shiftedKey: "Ы" },
       { code: "KeyD", key: "в", shiftedKey: "В" },
       { code: "KeyF", key: "а", shiftedKey: "А" },
       { code: "KeyG", key: "п", shiftedKey: "П" },
       { code: "KeyH", key: "р", shiftedKey: "Р" },
       { code: "KeyJ", key: "о", shiftedKey: "О" },
       { code: "KeyK", key: "л", shiftedKey: "Л" },
       { code: "KeyL", key: "д", shiftedKey: "Д" },
       { code: "Semicolon", key: "ж", shiftedKey: "Ж" },
       { code: "Quote", key: "э", shiftedKey: "Э" }
      ],
      [
       { code: "KeyZ", key: "я", shiftedKey: "Я" },
       { code: "KeyX", key: "ч", shiftedKey: "Ч" },
       { code: "KeyC", key: "с", shiftedKey: "С" },
       { code: "KeyV", key: "м", shiftedKey: "М" },
       { code: "KeyB", key: "и", shiftedKey: "И" },
       { code: "KeyN", key: "т", shiftedKey: "Т" },
       { code: "KeyM", key: "ь", shiftedKey: "Ь" },
       { code: "Comma", key: "б", shiftedKey: "Б" },
       { code: "Period", key: "ю", shiftedKey: "Ю" },
       { code: "Slash", key: "/", shiftedKey: "?" },     
      ],
    ]
  };